# Generated by Django 5.2.1 on 2025-05-16 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('bio', models.TextField(max_length=200)),
                ('sex', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('O', 'OTHER')], default='F', max_length=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
